export const authConstants = {
  USER_SIGNUP_REQUEST: 'USER_SIGNUP_REQUEST',
  USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_FAILURE: 'USER_SIGNUP_FAILURE',
  USER_SIGNIN_REQUEST: 'USER_SIGNIN_REQUEST',
  USER_SIGNIN_SUCCESS: 'USER_SIGNIN_SUCCESS',
  USER_SIGNIN_FAILURE: 'USER_SIGNIN_FAILURE',
  USER_SIGNOUT_REQUEST: 'USER_SIGNOUT_REQUEST',
  USER_SIGNOUT_SUCCESS: 'USER_SIGNOUT_SUCCESS',
  USER_SIGNOUT_FAILURE: 'USER_SIGNOUT_FAILURE'
};

export const userConstants = {
  GET_ALL_USER: 'GET_ALL_USER',
  GET_ALL_USER_SUCCESS: 'GET_ALL_USER_SUCCESS',
  GET_ALL_USER_FAILURE: 'GET_ALL_USER_FAILURE',
  GET_A_USER: 'GET_A_USER',
  GET_A_USER_SUCCESS: 'GET_A_USER_SUCCESS',
  GET_A_USER_FAILURE: 'GET_A_USER_FAILURE'
};

export const alertConstants = {
  ADD_ALERT: 'ADD_ALERT',
  CLOSE_ALERT: 'CLOSE_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT'
};
